[functions]
  external_node_modules = ["express",socket.io]
  node_bundler = "esbuild"
[[redirects]]
  from = "/socket.io/*"
  to = "/.netlify/functions/socket.io/:splat"
  status = 200

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/:splat"
  status = 200
