[functions]
  external_node_modules = ["express",socket.io]
  node_bundler = "esbuild"

[[redirects]]
  force = true
  from = "/socket.io/*"
  to = "/.netlify/functions/socket.io/:splat"
  status = 200

[[redirects]]
  force = true
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200

